# <center>NumPy</center>

## What is NumPy

#### NumPy, which stands for Numerical Python, is a powerful and widely-used library in the Python programming language, designed for numerical and scientific computing. 
#### NumPy provides an N-dimensional array object (ndarray) for efficient storage and manipulation of large numerical datasets.
#### Includes a wide range of mathematical operations, from basic arithmetic to advanced linear algebra and statistical functions.
#### Serves as the backbone for many other Python libraries like SciPy, pandas, and scikit-learn etc..

### Install NumPy

In [ ]:
pip install numpy

### Import NumPy Package

In [1]:
import numpy as np

### Creating a List

In [2]:
stock_values = [20.3, 25.3, 22.7, 19, 18.5, 21.2, 24.5, 26.6, 23.2, 21.2] # This is a list  Hetrogenius Data Value 
print(stock_values)
print(type(stock_values))

[20.3, 25.3, 22.7, 19, 18.5, 21.2, 24.5, 26.6, 23.2, 21.2]
<class 'list'>


### Converting List to NumPy Array

In [3]:
stock_arr = np.array(stock_values)  # Homogenious Data Value
print(stock_arr)
print(type(stock_arr))

[20.3 25.3 22.7 19.  18.5 21.2 24.5 26.6 23.2 21.2]
<class 'numpy.ndarray'>


### Display Dimension of Array

In [4]:
stock_arr.ndim

1

### Creating 2-Dimensional NumPy Array from List 

In [5]:
data_2 = [[1,2,3],[3,4,5]]
data_arr = np.array(data_2)

### Display 2-Dimensional Array Values

In [6]:
data_arr

array([[1, 2, 3],
       [3, 4, 5]])

### Display Dimension of Array

In [7]:
data_arr.ndim

2

### Display the Shape of any Array

In [8]:
data_arr.shape

(2, 3)

### Creating Two Lists and Concatenate

In [9]:
l1= [100,200,300]
l2 =[10,20,30]
l1 + l2 # It performs concatenation

[100, 200, 300, 10, 20, 30]

### Creating Two NumPy Arrays and Concatenate

In [10]:
n1 = np.array([100,200,300])
n2 = np.array([10,20,30])
n1 + n2 #It perform Matrix Addition 

array([110, 220, 330])

### Concatenate List with Value 

In [11]:
l1= [100,200,300] + 3 #Give Error Saying "can only concatenate list (not "int") to list"

TypeError: can only concatenate list (not "int") to list

### Concatenate NumPy Array with Value 

In [12]:
n1 + 3 # It perform Matrix Addition it add value to each element in Matrix

array([103, 203, 303])

### Accessing NumPy Array

In [13]:
data = [[1,2,3],[3,4,5]]
data_arr = np.array(data)

### Display complete array or matrix

In [14]:
data_arr

array([[1, 2, 3],
       [3, 4, 5]])

### Access NumPy Array using Index

In [17]:
print(data_arr[0][1])
print(data_arr[1][1])
print(data_arr[1,0])

2
4
3
