# <center>NumPy Copy vs NumPy View</center>

## NumPy View

In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6]) #1-Dimensional Array
print(x)
print(x.ndim)
print(x.shape)

[1 2 3 4 5 6]
1
(6,)


### Create a NumPy View from NumPy Array by performing Slicing

In [3]:
x_new = x[2:5]
print(x_new)

[3 4 5]


### Perform modification on NumPy View

In [4]:
x_new[:] = 0
print(x_new)

[0 0 0]


In [5]:
print(x)

[1 2 0 0 0 6]


## NumPy Copy

In [6]:
y = np.array([5,6,7,8,9])
print(y)

[5 6 7 8 9]


In [7]:
y_new = y[2:5].copy()
print(y_new)

[7 8 9]


### Perform Modification on NumPy Copy

In [8]:
y_new[:] = 0
print(y_new)

[0 0 0]


In [9]:
print(y)

[5 6 7 8 9]
